export function get(obj: any, path: string | string[], def?: any): any;
export function set(obj: any, path: string | string[], val: any): any;
export function pick<T extends object, K extends keyof T>(obj: T, keys: K[]): Pick<T, K>;
export function omit<T extends object, K extends keyof T>(obj: T, keys: K[]): Omit<T, K>;
export function merge<T>(target: T, ...sources: Partial<T>[]): T;
export function cloneDeep<T>(obj: T): T;
export function isEqual(a: any, b: any): boolean;
export function isEmpty(val: any): boolean;
export function has(obj: any, path: string): boolean;
export function chunk<T>(arr: T[], size: number): T[][];
export function compact<T>(arr: (T | null | undefined | false | 0 | '')[]): T[];
export function flatten<T>(arr: T[][]): T[];
export function flattenDeep(arr: any[]): any[];
export function uniq<T>(arr: T[]): T[];
export function uniqBy<T>(arr: T[], fn: ((item: T) => any) | string): T[];
export function sortBy<T>(arr: T[], fn: ((item: T) => any) | string): T[];
export function groupBy<T>(arr: T[], fn: ((item: T) => string) | string): Record<string, T[]>;
export function keyBy<T>(arr: T[], fn: ((item: T) => string) | string): Record<string, T>;
export function find<T>(arr: T[], fn: ((item: T) => boolean) | Partial<T>): T | undefined;
export function range(start: number, end?: number, step?: number): number[];
export function debounce<T extends (...args: any[]) => any>(fn: T, ms: number, opts?: { leading?: boolean }): T;
export function throttle<T extends (...args: any[]) => any>(fn: T, ms: number): T;
export function once<T extends (...args: any[]) => any>(fn: T): T;
export function memoize<T extends (...args: any[]) => any>(fn: T, resolver?: (...args: any[]) => any): T & { cache: Map<any, any> };
export function camelCase(s: string): string;
export function kebabCase(s: string): string;
export function snakeCase(s: string): string;
export function capitalize(s: string): string;
export function isArray(v: any): v is any[];
export function isObject(v: any): v is object;
export function isFunction(v: any): v is Function;
export function isString(v: any): v is string;
export function isNumber(v: any): v is number;
export function isNil(v: any): v is null | undefined;
export function isPlainObject(v: any): boolean;
export function noop(): void;
export function identity<T>(v: T): T;
declare const _: typeof import('./index') & ((v: any) => any);
export default _;
